### PR TITLE
Lastest fixes

### PR DESCRIPTION
**Pull request by xendk**
Fixes some redmine issus.

### CODE REVIEW

**Comment by cableman** [comment]
Reviewed and approved

**Comment by guddo** [comment]
Anyone got Redmine referrals to these fixes?

**Comment by xendk** [comment]
Why do you need an issue?

**Comment by guddo** [comment]
To understand if there is a business perspective on using deprecated reservation functionality :)

**Comment by xendk** [comment]
There's an issue now. 

I'm pretty sure most of these fixes were out of band of Redmine. I think there was at least 3 bug trackers involved in the project at some point, in addition to the old email-of-issues..

**Pull request merged**
